<?php
// module/Album/view/album/album/delete.phtml:

$model = 'Usuń pojazd';
$url   = $this->url('komis', ['action' => 'delete', 'id' => $id]);

$this->headTitle($model);
?>
<h1>Usuń samochód</h1>

<p>
	Czy na pewno chcesz usunąć samochód marki  
    <?= $this->escapeHtml($komis->marka) ?>  
    <?= $this->escapeHtml($komis->model) ?>?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $komis->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>