<?php
// module/Album/view/album/album/edit.phtml:

$model = 'Edit komis';
$this->headTitle($model);
?>
<h1>Edit Car</h1>
<?php
$komis = $form->get('model');
$komis->setAttribute('class', 'form-control');
$komis->setAttribute('placeholder', 'Komis model');

$marka = $form->get('marka');
$marka->setAttribute('class', 'form-control');
$marka->setAttribute('placeholder', 'Marka');

$img = $form->get('img');
$img->setAttribute('class', 'form-control');
$img->setAttribute('placeholder', 'Img URL');

$year = $form->get('year');
$year->setAttribute('class', 'form-control');
$year->setAttribute('placeholder', 'Rok');

$desc = $form->get('desc');
$desc->setAttribute('class', 'form-control');
$desc->setAttribute('placeholder', 'Opis');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('komis', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($marka) ?>
    <?= $this->formElement($marka) ?>
    <?= $this->formElementErrors()->render($marka, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($komis) ?>
    <?= $this->formElement($komis) ?>
    <?= $this->formElementErrors()->render($komis, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($year) ?>
    <?= $this->formElement($year) ?>
    <?= $this->formElementErrors()->render($year, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($desc) ?>
    <?= $this->formElement($desc) ?>
    <?= $this->formElementErrors()->render($desc, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($img) ?>
    <?= $this->formElement($img) ?>
    <?= $this->formElementErrors()->render($img, ['class' => 'help-block']) ?>
</div>


<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();