<h1>O nas</h1> 

<p>Aenean mauris ipsum, ornare vel dui vel, ullamcorper gravida nibh. Nam quis faucibus lectus. Suspendisse posuere fringilla elit, vel auctor dolor sodales at. Duis varius auctor vulputate. In auctor rutrum justo eget viverra. Suspendisse eleifend vitae nunc quis varius. Aliquam cursus mi id metus ultrices tincidunt. Aliquam convallis tellus odio, non eleifend felis facilisis eget. Nulla facilisi. Curabitur vitae erat dignissim, placerat erat at, molestie ligula. Donec vitae tincidunt ipsum, non euismod dui. Suspendisse ut tristique metus, accumsan egestas tellus. Vestibulum ac pharetra elit.</p>

<p>Nullam tristique porttitor diam, sed facilisis lectus placerat quis. Nullam turpis est, gravida eu justo nec, mattis consequat velit. Donec fermentum nibh quis lacus posuere iaculis. Curabitur aliquet sem in velit porttitor, a sagittis ex elementum. Aenean in metus eget sapien varius suscipit lacinia nec risus. Etiam metus enim, tincidunt ut rhoncus a, dictum sit amet nibh. Maecenas ornare vehicula lacus, eget ultrices nulla convallis non. Integer pellentesque sed massa at hendrerit. Curabitur et bibendum risus. Praesent eget tellus ut velit ullamcorper dapibus. Pellentesque ultrices mauris at tincidunt pulvinar.</p>

<div>
	<a href="<?= $this->url('komis', ['action' => 'index', 'id' => $komis->id]) ?>">Wróc</a>
</div>